#Entryway Group
entryway_sensor_group:
  name: Entryway Sensors
  control: hidden
  view: no
  entities: 
    - sensor.front_door_state
    - sensor.front_door_tamper
    - sensor.entryway_sensor_luminance
    - sensor.entryway_sensor_relative_humidity
    - sensor.entryway_sensor_temperature
    - sensor.entryway_multisensor_motion
    - sensor.entryway_multisensor_tamper
    - sensor.entryway_multisensor_batterylevel
