#Motion Group
motion_sensors:
  name: Motion Sensors
  control: hidden
  view: no
  entities:
    - sensor.garage_multisensor_motion 
    - sensor.entryway_multisensor_motion
    - sensor.mainfloor_multisensor_motion
    - sensor.basement_multisensor_motion
