  garage_door:
    name: Garage is open
    done_message: Garage is closed
    entity_id: cover.garage_door_barrier_state_label
    state: 'open'
    repeat:
      - 15
      - 30
      - 60
    can_acknowledge: true
    skip_first: false
    notifiers:
      - admin_phone
