#SSL Warning Automation
 - alias: 'SSL expiry notification'
   trigger:
     platform: numeric_state
     entity_id: sensor.ssl_cert_expiry
     below: 21
   action:
     service: notify.notify
     data:
       message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'
   
 - alias: 'Notify on Failed Login'
   trigger:
     - platform: state
       entity_id: sensor.fail2ban_ssh
     - platform: state
       entity_id: sensor.fail2ban_hassiptables
   condition:
     condition: or
     conditions:
       - condition: template
         value_template: '{{ states.sensor.fail2ban_ssh.state != "None" }}'
       - condition: template
         value_template: '{{ states.sensor.fail2ban_hassiptables.state != "None" }}'
   action:
     - service: notify.notify
       data_template:
         message: >
           Failed Login! {{ now().strftime("%h %d, %Y at %H:%M:%S") }}
           {% if states.sensor.fail2ban_ssh.state != "None" %}
             SSH Attempt(s) from {{states.sensor.fail2ban_ssh.state}}
           {% endif %}
           {% if states.sensor.fail2ban_hassiptables.state != "None" %}
             Web Attempt(s) from {{states.sensor.fail2ban_hassiptables.state}}
           {% endif %}
         target: !secret adminPhone
