  zwave.aeotec_zw090_zstick_gen5_us:
     hidden: true
  zwave.fan:
    hidden: true
  zwave.light:
    hidden: true
  zwave.outlet1:
    hidden: true
  zwave.outlet2:
    hidden: true
  zwave.thermostat:
    hidden: true
  zwave.guest_room_light:
    hidden: true
  zwave.porch_light:
    hidden: true
  #zwave.basement_sensor:
  #  hidden: true
  #zwave.entryway_sensor:
  #  hidden: true
  #zwave.garage_sensor:
  #  hidden: true
  #zwave.main_floor_sensor:
  #  hidden: true
  sensor.basement_sensor_alarm_type:
    hidden: true
  sensor.basement_sensor_alarm_level:
    hidden: true
  sensor.basement_sensor_appliance:
    hidden: true
  sensor.basement_sensor_burglar:
    hidden: true
  sensor.basement_sensor_emergency:
    hidden: true
  sensor.basement_sensor_homehealth:
    hidden: true
  sensor.basement_sensor_sourcenodeid:
    hidden: true
  sensor.basement_sensor_system:
    hidden: true
  binary_sensor.basement_sensor_sensor:
    hidden: true
  sensor.basement_sensor_luminance:
    friendly_name: Basement Luminance
  sensor.basement_sensor_relative_humidity:
    friendly_name: Basement Relative Humidity
  sensor.basement_sensor_temperature:
    friendly_name: Basement Temperature
  sensor.main_floor_sensor_alarm_type:
    hidden: true
  sensor.main_floor_sensor_alarm_level:
    hidden: true
  sensor.main_floor_sensor_appliance:
    hidden: true
  sensor.main_floor_sensor_burglar:
    hidden: true
  sensor.main_floor_sensor_emergency:
    hidden: true
  sensor.main_floor_sensor_homehealth:
    hidden: true
  sensor.main_floor_sensor_sourcenodeid:
    hidden: true
  sensor.main_floor_sensor_system:
    hidden: true
  binary_sensor.main_floor_sensor_sensor:
    hidden: true
  sensor.main_floor_sensor_power_management:
    hidden: true
  sensor.main_floor_sensor_clock:
    hidden: true
  sensor.main_floor_sensor_luminance:
    friendly_name: Main Floor Luminance
  sensor.main_floor_sensor_relative_humidity:
    friendly_name: Main Floor Relative Humidity
  sensor.main_floor_sensor_temperature:
    friendly_name: Main Floor Temperature
  sensor.entryway_sensor_alarm_type:
    hidden: true
  sensor.entryway_sensor_alarm_level:
    hidden: true
  sensor.entryway_sensor_appliance:
    hidden: true
  sensor.entryway_sensor_burglar:
    hidden: true
  sensor.entryway_sensor_emergency:
    hidden: true
  sensor.entryway_sensor_homehealth:
    hidden: true
  sensor.entryway_sensor_sourcenodeid:
    hidden: true
  sensor.entryway_sensor_system:
    hidden: true
  binary_sensor.entryway_sensor_sensor:
    hidden: true
  sensor.entryway_sensor_power_management:
    hidden: true
  sensor.entryway_sensor_clock:
    hidden: true
  sensor.entryway_sensor_luminance:
    friendly_name: Entryway Luminance
  sensor.entryway_sensor_relative_humidity:
    friendly_name: Entryway Relative Humidity
  sensor.entryway_sensor_temperature:
    friendly_name: Entryway Temperature
  sensor.garage_sensor_alarm_type:
    hidden: true
  sensor.garage_sensor_alarm_level:
    hidden: true
  sensor.garage_sensor_appliance:
    hidden: true
  sensor.garage_sensor_burglar:
    hidden: true
  sensor.garage_sensor_emergency:
    hidden: true
  sensor.garage_sensor_homehealth:
    hidden: true
  sensor.garage_sensor_sourcenodeid:
    hidden: true
  sensor.garage_sensor_system:
    hidden: true
  binary_sensor.garage_sensor_sensor:
    hidden: true
  sensor.garage_sensor_power_management:
    hidden: true
  switch.garage_sensor_switch:
    hidden: true
  sensor.garage_sensor_luminance:
    friendly_name: Garage Luminance
  sensor.garage_sensor_relative_humidity:
    friendly_name: Garage Relative Humidity
  sensor.garage_sensor_temperature:
    friendly_name: Garage Temperature
  sensor.thermostat_temperature:
    hidden: true
  climate.thermostat_away_heating:
    friendly_name: Away Heating
  climate.thermostat_cooling_1:
    friendly_name: Cooling
  climate.thermostat_cooling_econ:
    friendly_name: Away Cooling
  climate.thermostat_unused_3:
    friendly_name: Heating
  switch.light_switch:
    friendly_name: Bedroom Light Switch
  switch.guest_room_light_switch:
    friendly_name: Guest Room Light Switch
  switch.outlet1_switch:
    friendly_name: Main Level Outlet 1
  switch.outlet2_switch:
    friendly_name: Main Level Outlet 2
