default_view:
  view: yes
  icon: mdi:home 
  entities:
    - group.alarm_clock
    - group.smoke_detectors
    - group.all_devices
    - group.all_switches
    - group.all_fans
    - group.all_covers

entryway:
  name: Entryway
  view: yes
  entities:
    - switch.porch_light_switch      
    - group.entryway_sensor_group
    - media_player.front_entryway_home

garage:
  name: Garage
  view: yes
  entities:
    - group.garage_sensor_group
    - cover.garage_door_barrier_state_label

bedroom:
  name: Bedroom
  view: yes
  entities:
    - switch.bedroom_light_switch
    - fan.bedroom_fan_level

guestroom:
  name: Guest Room
  view: yes
  entities:
    - switch.guest_room_light_switch

basement:
  name: Basement
  control: hidden
  view: yes
  entities:
    - group.basment_sensor_group
    - light.basement_light
    - media_player.basement_speaker
    - media_player.basement_tv
    - media_player.basement
    - media_player.txrz800

mainlevel:
  name: Main Floor
  control: hidden
  view: yes
  entities:
    - switch.outlet_1_switch
    - switch.outlet_2_switch
    - group.mainfloor_sensor_group
    - group.entryway_sensor_group

climate:
  name: Climate
  control: hidden
  view: yes
  entities:
    - group.daily_forecast
    - group.climate_sensor_group
    - group.weather_overview
    - group.room_climate_group

zwave:
  name: ZWave
  control: hidden
  view: yes
  entities:
    - zwave.aeotec_zw090_zstick_gen5_us
    - zwave.bedroom_fan
    - zwave.bedroom_light
    - zwave.outlet_1
    - zwave.outlet_2
    - zwave.thermostat
    - zwave.guest_room_light
    - zwave.porch_light
    - zwave.basement_sensor
    - zwave.entryway_sensor
    - zwave.garage_sensor
    - zwave.garage_door
    - zwave.main_floor_sensor
    - zwave.entryway_smoke_detector
    - group.battery_sensor_group
    - group.test_stuff

automations:
  name: automations
  view: yes
  entities:
    - group.battery_alert
    - automation.ssl_expiry_notification
    - automation.notify_on_failed_login

battery_sensor_group:
  name: Battery Levels
  control: hidden
  view: no
  entities:
    - sensor.basement_sensor_battery
    - sensor.entryway_sensor_battery
    - sensor.garage_sensor_battery
    - sensor.main_floor_sensor_battery
    - sensor.thermostat_battery
    - sensor.entryway_smoke_detector_battery

smoke_detectors:
  name: Smoke Detectors
  control: hidden
  view: no
  entities:
    - sensor.entryway_smoke_co2

test_stuff:
  name: Testing Stuff
  control: hidden
  view: no
  entities:
    - sensor.entryway_smoke_detector_alarm_level
    - sensor.entryway_smoke_detector_alarm_type

climate_sensor_group:
  name: HVAC
  control: hidden
  view: no
  entities:
    - climate.thermostat_heating_1
    - climate.thermostat_cooling_1

room_climate_group:
  name: Room Climate
  control: hidden
  view: no
  entities:
    - sensor.basement_sensor_temperature
    - sensor.basement_sensor_relative_humidity
    - sensor.main_floor_sensor_temperature
    - sensor.main_floor_sensor_relative_humidity
    - sensor.entryway_sensor_temperature
    - sensor.entryway_sensor_relative_humidity
    - sensor.garage_sensor_temperature
    - sensor.garage_sensor_relative_humidity

basment_sensor_group:
  name: Basement Sensors
  control: hidden
  view: no
  entities:
    - sensor.basement_sensor_luminance
    - sensor.basement_sensor_relative_humidity
    - sensor.basement_sensor_temperature
    - sensor.basement_multisensor_motion
    - sensor.basement_multisensor_tamper 
    - sensor.basement_multisensor_batterylevel

mainfloor_sensor_group:
  name: Main Floor Sensors
  control: hidden
  view: no
  entities:
    - sensor.main_floor_sensor_luminance
    - sensor.main_floor_sensor_relative_humidity
    - sensor.main_floor_sensor_temperature
    - sensor.mainfloor_multisensor_motion
    - sensor.mainfloor_multisensor_tamper
    - sensor.mainfloor_multisensor_batterylevel

entryway_sensor_group:
  name: Entryway Sensors
  control: hidden
  view: no
  entities:
    - sensor.entryway_sensor_luminance
    - sensor.entryway_sensor_relative_humidity
    - sensor.entryway_sensor_temperature
    - sensor.entryway_multisensor_motion
    - sensor.entryway_multisensor_tamper
    - sensor.entryway_multisensor_batterylevel

garage_sensor_group:
  name: Garage Sensors
  control: hidden
  view: no
  entities:
    - sensor.garage_sensor_luminance
    - sensor.garage_sensor_relative_humidity
    - sensor.garage_sensor_temperature
    - sensor.garage_multisensor_motion
    - sensor.garage_multisensor_tamper
    - sensor.garage_multisensor_batterylevel

daily_forecast:
  name: Daily Forecast
  control: hidden
  view: no
  entities:
    - sensor.pws_weather_1d
    - sensor.pws_weather_1n
    - sensor.pws_weather_2d
    - sensor.pws_weather_2n

weather_overview:
  name: Weather overview
  control: hidden
  view: no
  entities:
    - sensor.pws_temp_high_1d_f
    - sensor.pws_temp_f
    - sensor.pws_temp_low_1d_f
    - sensor.pws_precip_1d
    - sensor.pws_precip_1d_in
    - sensor.pws_wind_mph
    - sensor.pws_wind_1d_mph
    - sensor.pws_alerts
# Alarm clock
alarm_clock:
  name: 'Alarm Clock'
  entities:
    - sensor.alarm_clock_time
    - input_number.alarm_clock_hour
    - input_number.alarm_clock_minute
    - input_boolean.alarm_clock_status
