default_view:
  view: no
  icon: mdi:home 
  entities:
    - group.entryway
    - group.bedroom
    - group.guestroom
    - group.basement
    - group.mainlevel
    - group.climate

entryway:
  name: Entryway
  view: yes
  entities:
    - group.entryway_sensor_group
    - media_player.front_entryway_home

bedroom:
  name: Bedroom
  view: yes
  entities:
    - switch.light_switch
    - fan.fan_level

guestroom:
  name: Guest Room
  view: yes
  entities:
    - switch.guest_room_light_switch

basement:
  name: Basement
  control: hidden
  view: yes
  entities:
    - group.basment_sensor_group
    - light.basement_light
    - media_player.basement_home
    - media_player.basement_tv
    - media_player.living_room
    - media_player.txrz800

mainlevel:
  name: Main Floor
  control: hidden
  view: yes
  entities:
    - switch.outlet1_switch
    - switch.outlet2_switch
    - group.mainfloor_sensor_group
    - group.entryway_sensor_group
    - group.garage_sensor_group

climate:
  name: Climate
  control: hidden
  view: yes
  entities:
    - group.daily_forecast
    - group.climate_sensor_group
    - group.weather_overview
    - group.room_climate_group

climate_sensor_group:
  name: HVAC
  control: hidden
  view: no
  entities:
    - climate.thermostat_cooling_1
    - climate.thermostat_heating_1

room_climate_group:
  name: Room Climate
  control: hidden
  view: no
  entities:
    - sensor.basement_sensor_temperature
    - sensor.basement_sensor_relative_humidity
    - sensor.main_floor_sensor_temperature
    - sensor.main_floor_sensor_relative_humidity
    - sensor.entryway_sensor_temperature
    - sensor.entryway_sensor_relative_humidity
    - sensor.garage_sensor_temperature
    - sensor.garage_sensor_relative_humidity

basment_sensor_group:
  name: Basement Sensors
  control: hidden
  view: no
  entities:
    - sensor.basement_sensor_luminance
    - sensor.basement_sensor_relative_humidity
    - sensor.basement_sensor_temperature
    - sensor.basement_multisensor_motion
    - sensor.basement_multisensor_tamper 
    - sensor.basement_multisensor_batterylevel

mainfloor_sensor_group:
  name: Main Floor Sensors
  control: hidden
  view: no
  entities:
    - sensor.main_floor_sensor_luminance
    - sensor.main_floor_sensor_relative_humidity
    - sensor.main_floor_sensor_temperature
    - sensor.mainfloor_multisensor_motion
    - sensor.mainfloor_multisensor_tamper
    - sensor.mainfloor_multisensor_batterylevel

entryway_sensor_group:
  name: Entryway Sensors
  control: hidden
  view: no
  entities:
    - sensor.entryway_sensor_luminance
    - sensor.entryway_sensor_relative_humidity
    - sensor.entryway_sensor_temperature
    - sensor.entryway_multisensor_motion
    - sensor.entryway_multisensor_tamper
    - sensor.entryway_multisensor_batterylevel

garage_sensor_group:
  name: Garage Sensors
  control: hidden
  view: no
  entities:
    - sensor.garage_sensor_luminance
    - sensor.garage_sensor_relative_humidity
    - sensor.garage_sensor_temperature
    - sensor.garage_multisensor_motion
    - sensor.garage_multisensor_tamper
    - sensor.garage_multisensor_batterylevel

daily_forecast:
  name: Daily Forecast
  control: hidden
  view: no
  entities:
    - sensor.pws_weather_1d
    - sensor.pws_weather_1n
    - sensor.pws_weather_2d
    - sensor.pws_weather_2n

weather_overview:
  name: Weather overview
  control: hidden
  view: no
  entities:
    - sensor.pws_temp_high_1d_f
    - sensor.pws_temp_f
    - sensor.pws_temp_low_1d_f
    - sensor.pws_precip_1d
    - sensor.pws_precip_1d_in
    - sensor.pws_wind_mph
    - sensor.pws_wind_1d_mph
    - sensor.pws_alerts
