###########################
# SENSORS                 #
###########################
- platform: template
  sensors:  
    basement_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.basement_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    basement_multisensor_tamper:
      friendly_name: 'Basement Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.basement_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    mainfloor_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.main_floor_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    mainfloor_multisensor_tamper:
      friendly_name: 'Main Floor Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.main_floor_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    garage_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.garage_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    garage_multisensor_tamper:
      friendly_name: 'Garage Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.garage_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    entryway_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.entryway_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    entryway_multisensor_tamper:
      friendly_name: 'Entryway Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.entryway_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    front_door_tamper:
      friendly_name: 'Front Door Tampering'
      value_template: >-
          {%- if is_state("sensor.front_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    front_door_state:
      friendly_name: 'Front Door'
      value_template: >-
          {%- if is_state("sensor.front_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.front_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    kitchen_door_tamper:
      friendly_name: 'Kitchen Door Tampering'
      value_template: >-
          {%- if is_state("kitchen.front_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    kitchen_door_state:
      friendly_name: 'Kitchen Door'
      value_template: >-
          {%- if is_state("sensor.kitchen_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.kitchen_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    entryway_smoke_co2:
      friendly_name: 'Entryway Smoke Alarm'
      value_template: >- 
          {%- if is_state("sensor.entryway_smoke_detector_alarm_level", "0") -%}
              Idle
          {%- else -%}
            {%- if is_state("sensor.entryway_smoke_detector_alarm_type", "1") -%}
                Fire
            {%- elif is_state("sensor.entryway_smoke_detector_alarm_type", "2") -%}
                C02
            {%- elif is_state("sensor.entryway_smoke_detector_alarm_type", "12") -%}
                Testing
            {%- elif is_state("sensor.entryway_smoke_detector_alarm_type", "13") -%}
                Idle
            {%- else -%}
                Unknown
            {%- endif -%}
          {%- endif -%} 
- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - temp_high_1d_f
    - temp_f
    - temp_low_1d_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts
- platform: fail2ban
  jails:
    - hass-iptables
    - ssh   
  file_path: /etc/fail2ban/log/fail2ban.log
  scan_interval: 60
#ALARM CLOCK SENSORS
- platform: time_date
  display_options:
    - 'time'
- platform: template
  sensors:
    alarm_clock_hour:
      value_template: '{{ states.input_number.alarm_clock_hour.state | int }}'
    alarm_clock_minute:
      value_template: '{{ states.input_number.alarm_clock_minute.state | int }}'
    alarm_clock_time:
      value_template: >-
        {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}
    alarm_clock_time_long:
      value_template: >-
        {% if states.sensor.alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}
##### Plant Link (Marilyn)
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  name: Plant Name
  value_template: '{{ value_json.name }}'
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  name: Marilyn Status
  value_template: >
         {% if value_json.status | int == 0 %}
           Too Dry
         {% elif value_json.status | int == 1 %}
           Dry
         {% elif value_json.status | int == 2 %}
           Optimal
         {% elif value_json.status | int == 3 %}
           Wet
         {% elif value_json.status | int == 4 %}
           Too Wet
         {% else %}
           value_json.status
         {% endif %}
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  name: Marilyn Moisture
  sensor_class: moisture
  unit_of_measurement: '%'
  value_template: '{{ ((value_json.last_measurements[0]["moisture"]) * 100) | round(0) }}'
