  usb_path: /dev/ttyACM0
  config_path: /usr/local/lib/python3.5/dist-packages/python_openzwave/ozw_config
  debug: false
  new_entity_ids: true
  network_key: !secret zwave_key
  polling_interval: 45000
