###########################
# Basement Sensor
###########################
- platform: template
  sensors:  
    basement_multisensor_motion:
      friendly_name: 'Basement Motion'
      entity_id: sensor.basement_sensor_burglar
      value_template: >-
          {%- if is_state("sensor.basement_sensor_burglar", "0") -%}
              Clear
          {%- else -%}
              Detected
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.basement_sensor_burglar", "0") -%}
              mdi:walk
          {%- else -%}
              mdi:run-fast
          {%- endif -%}
    basement_multisensor_tamper:
      friendly_name: 'Basement Sensor Tampering'
      entity_id: sensor.basement_sensor_burglar
      value_template: >-
          {%- if is_state("sensor.basement_sensor_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.basement_sensor_burglar", "3") -%}
              mdi:alert-outline
          {%- else -%}
              mdi:triangle-outline
          {%- endif -%}
