###########################
# Basement Sensor
###########################
- platform: template
  sensors:  
    basement_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.basement_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    basement_multisensor_tamper:
      friendly_name: 'Basement Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.basement_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
