###########################
# Entryway Sensor
###########################
- platform: template
  sensors:  
    entryway_multisensor_motion:
      friendly_name: 'Entryway Motion'
      entity_id: sensor.entryway_sensor_burglar
      value_template: >-
          {%- if is_state("sensor.entryway_sensor_burglar", "0") -%}
              Clear
          {%- else -%}
              Detected
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.entryway_sensor_burglar", "0") -%}
              mdi:walk
          {%- else -%}
              mdi:run-fast
          {%- endif -%}
    entryway_multisensor_tamper:
      friendly_name: 'Entryway Sensor Tampering'
      entity_id: sensor.entryway_sensor_burglar
      value_template: >-
          {%- if is_state("sensor.entryway_sensor_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.entryway_sensor_burglar", "3") -%}
              mdi:alert-outline
          {%- else -%}
              mdi:triangle-outline
          {%- endif -%}

