###########################
# Mainfloor Sensor
###########################
- platform: template
  sensors:  
    mainfloor_multisensor_motion:
      friendly_name: 'Main Floor Motion'
      entity_id: sensor.main_floor_sensor_burglar
      value_template: >-
          {%- if is_state("sensor.main_floor_sensor_burglar", "0") -%}
              Clear
          {%- else -%}
              Detected
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.main_floor_sensor_burglar", "0") -%}
              mdi:walk
          {%- else -%}
              mdi:run-fast
          {%- endif -%}
    mainfloor_multisensor_tamper:
      friendly_name: 'Main Floor Sensor Tampering'
      entity_id: sensor.main_floor_sensor_burglar
      value_template: >-
          {%- if is_state("sensor.main_floor_sensor_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.main_floor_sensor_burglar", "3") -%}
              mdi:alert-outline
          {%- else -%}
              mdi:triangle-outline
          {%- endif -%}

