###########################
# Door Sensors                 
###########################
- platform: template
  sensors:  
    front_door_tamper:
      friendly_name: 'Front Door Tampering'
      value_template: >-
          {%- if is_state("sensor.front_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    front_door_state:
      friendly_name: 'Front Door'
      value_template: >-
          {%- if is_state("sensor.front_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.front_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    kitchen_door_tamper:
      friendly_name: 'Kitchen Door Tampering'
      value_template: >-
          {%- if is_state("sensor.kitchen_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    kitchen_door_state:
      friendly_name: 'Kitchen Door'
      value_template: >-
          {%- if is_state("sensor.kitchen_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.kitchen_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    game_room_main_door_tamper:
      friendly_name: 'Game Room Main Door Tampering'
      value_template: >-
          {%- if is_state("sensor.game_room_main_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    game_room_main_door_state:
      friendly_name: 'Game Room Main Door'
      value_template: >-
          {%- if is_state("sensor.game_room_main_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.game_room_main_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    game_room_side_door_tamper:
      friendly_name: 'Game Room Side Door Tampering'
      value_template: >-
          {%- if is_state("sensor.game_room_side_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    game_room_side_door_state:
      friendly_name: 'Game Room Side Door'
      value_template: >-
          {%- if is_state("sensor.game_room_side_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.game_room_side_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
