###########################
# SENSORS                 #
###########################
- platform: template
  sensors:  
    basement_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.basement_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    basement_multisensor_tamper:
      friendly_name: 'Basement Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.basement_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    mainfloor_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.main_floor_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    mainfloor_multisensor_tamper:
      friendly_name: 'Main Floor Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.main_floor_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    garage_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.garage_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    garage_multisensor_tamper:
      friendly_name: 'Garage Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.garage_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    entryway_multisensor_motion:
      friendly_name: 'Motion Detected?'
      value_template: >-
          {%- if is_state("sensor.entryway_sensor_burglar", "0") -%}
              No
          {%- else -%}
              Yes
          {%- endif -%}
    entryway_multisensor_tamper:
      friendly_name: 'Entryway Sensor Tampering'
      value_template: >-
          {%- if is_state("sensor.entryway_sensor_burgler", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    front_door_tamper:
      friendly_name: 'Front Door Tampering'
      value_template: >-
          {%- if is_state("sensor.front_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    front_door_state:
      friendly_name: 'Front Door'
      value_template: >-
          {%- if is_state("sensor.front_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.front_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    kitchen_door_tamper:
      friendly_name: 'Kitchen Door Tampering'
      value_template: >-
          {%- if is_state("sensor.kitchen_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    kitchen_door_state:
      friendly_name: 'Kitchen Door'
      value_template: >-
          {%- if is_state("sensor.kitchen_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.kitchen_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    game_room_main_door_tamper:
      friendly_name: 'Game Room Main Door Tampering'
      value_template: >-
          {%- if is_state("sensor.game_room_main_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    game_room_main_door_state:
      friendly_name: 'Game Room Main Door'
      value_template: >-
          {%- if is_state("sensor.game_room_main_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.game_room_main_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    game_room_side_door_tamper:
      friendly_name: 'Game Room Side Door Tampering'
      value_template: >-
          {%- if is_state("sensor.game_room_side_door_burglar", "3") -%}
              Yes
          {%- else -%}
              No
          {%- endif -%}
    game_room_side_door_state:
      friendly_name: 'Game Room Side Door'
      value_template: >-
          {%- if is_state("sensor.game_room_side_door_access_control", "23") -%}
              Closed
          {%- else -%}
              Open
          {%- endif -%}
      icon_template: >-
          {%- if is_state("sensor.game_room_side_door_access_control", "23") -%}
              mdi:door-closed
          {%- else -%}
              mdi:door-open
          {%- endif -%}
    entryway_smoke_co2:
      friendly_name: 'Entryway Smoke Alarm'
      value_template: >- 
          {%- if is_state("sensor.entryway_smoke_detector_alarm_level", "0") -%}
              Idle
          {%- else -%}
            {%- if is_state("sensor.entryway_smoke_detector_alarm_type", "1") -%}
                Fire
            {%- elif is_state("sensor.entryway_smoke_detector_alarm_type", "2") -%}
                C02
            {%- elif is_state("sensor.entryway_smoke_detector_alarm_type", "12") -%}
                Testing
            {%- elif is_state("sensor.entryway_smoke_detector_alarm_type", "13") -%}
                Idle
            {%- else -%}
                Unknown
            {%- endif -%}
          {%- endif -%} 
    basement_smoke_co2:
      friendly_name: 'Basement Smoke Alarm'
      value_template: >- 
          {%- if is_state("sensor.basement_smoke_detector_alarm_level", "0") -%}
              Idle
          {%- else -%}
            {%- if is_state("sensor.basement_smoke_detector_alarm_type", "1") -%}
                Fire
            {%- elif is_state("sensor.basement_smoke_detector_alarm_type", "2") -%}
                C02
            {%- elif is_state("sensor.basement_smoke_detector_alarm_type", "12") -%}
                Testing
            {%- elif is_state("sensor.basement_smoke_detector_alarm_type", "13") -%}
                Idle
            {%- else -%}
                Unknown
            {%- endif -%}
          {%- endif -%} 
    upstairs_smoke_co2:
      friendly_name: 'Upstairs Smoke Alarm'
      value_template: >- 
          {%- if is_state("sensor.upstairs_smoke_detector_alarm_level", "0") -%}
              Idle
          {%- else -%}
            {%- if is_state("sensor.upstairs_smoke_detector_alarm_type", "1") -%}
                Fire
            {%- elif is_state("sensor.upstairs_smoke_detector_alarm_type", "2") -%}
                C02
            {%- elif is_state("sensor.upstairs_smoke_detector_alarm_type", "12") -%}
                Testing
            {%- elif is_state("sensor.upstairs_smoke_detector_alarm_type", "13") -%}
                Idle
            {%- else -%}
                Unknown
            {%- endif -%}
          {%- endif -%} 
- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - temp_high_1d_f
    - temp_f
    - temp_low_1d_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts
- platform: fail2ban
  jails:
    - hass-iptables
    - ssh   
  file_path: /etc/fail2ban/log/fail2ban.log
  scan_interval: 60
#ALARM CLOCK SENSORS
- platform: template
  sensors:
    wakeup_alarm_time:
      friendly_name: 'Alarm time'
      value_template: '{% if states.input_number.wakeup_hour.state|length == 3 %}0{% endif %}{{ states.input_number.wakeup_hour.state | int }}:{% if states.input_number.wakeup_minutes.state|length == 3 %}0{% endif %}{{ states.input_number.wakeup_minutes.state | int }}'

- platform: template
  sensors:
    wakeup_start_time_lights:
      friendly_name: 'Fade-in start time'
      value_template: >
        {% if states.sensor.wakeup_alarm_time and states.input_number.wakeup_duration %}
        {% set alarmtime = states.sensor.wakeup_alarm_time.state %}
        {% set alarm_hour = alarmtime.split(":")[0] | int %}
        {% set alarm_min = alarmtime.split(":")[1] | int %}
        {% set light_dur = states.input_number.wakeup_duration.state | int %}
        {% set alarm_min_light = alarm_min - light_dur -10 %}
        {% if alarm_min_light  < 0 %}
        {% set alarm_min_light = alarm_min_light + 60 %}
        {% set alarm_hour_light = alarm_hour - 1 %}
        {% if alarm_hour_light < 0 %}{% set alarm_hour_light = 23 %}{% endif %}
        {% if alarm_hour_light < 10 %}0{% endif %}{{ alarm_hour_light}}:{% if alarm_min_light < 10 %}0{% endif %}{{ alarm_min_light }}
        {% else %}
        {% if alarm_hour < 10 %}0{% endif %}{{ alarm_hour }}:{% if alarm_min_light < 10 %}0{% endif %}{{ alarm_min_light }}
        {% endif %}
        {% endif %}

- platform: template
  sensors:
    wakeup_fadein_duration:
      friendly_name: 'Fade-in duration'
      value_template: '{{ states.input_number.wakeup_duration.state | int }}'
      unit_of_measurement: 'min'

- platform: time_date
  display_options:
    - 'time'
##### Plant Link (Marilyn)
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  name: Plant Name
  value_template: '{{ value_json.name }}'
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  name: Marilyn Status
  value_template: >
         {% if value_json.status | int == 0 %}
           Too Dry
         {% elif value_json.status | int == 1 %}
           Dry
         {% elif value_json.status | int == 2 %}
           Optimal
         {% elif value_json.status | int == 3 %}
           Wet
         {% elif value_json.status | int == 4 %}
           Too Wet
         {% else %}
           value_json.status
         {% endif %}
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  name: Marilyn Moisture
  sensor_class: moisture
  unit_of_measurement: '%'
  value_template: '{{ ((value_json.last_measurements[0]["moisture"]) * 100) | round(0) }}'
