#Automation View
#
automations:
  name: automations
  view: yes
  entities:
    - group.battery_alert
    - group.all_automations
#    - automation.ssl_expiry_notification
#    - automation.notify_on_failed_login
#    - automation.admin_arrived_home
#    - automation.user_arrived_home
#    - automation.away_mode
