#Main Floor View
#
mainlevel:
  name: Main Floor
  control: hidden
  view: yes
  entities:
    - switch.outlet_1_switch
    - switch.outlet_2_switch
    - group.mainfloor_sensor_group
    - group.entryway_sensor_group
