- alias: 'Front Door Opened At Night'
  trigger:
    platform: state
    entity_id: sensor.front_door_state
    to: 'Open'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-1:00:00"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.porch_light_switch
