- alias: 'Away Mode'
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id: group.all_fans,group.all_switches,group.all_lights
