#Weather Alert Automation
- alias: 'Wx Alert Notification'
  trigger:
    platform: state
    entity_id: sensor.pws_alerts
  action:
    service: script.notifyonwxalert

#Notify on Severe Weather
- alias: TTS and Notify Weather Alert
  trigger:
    platform: numeric_state
    entity_id: sensor.pws_alerts
    above: 0
  action:
    - service: tts.google_say
      data_template:
        entity_id:
          - media_player.bedroom_home
          - media_player.guest_room_speaker
          - media_player.basement_speaker
          - media_player.guest_room_speaker
        message: "The National Weather Service has issued a 
        {{ states.sensor.pws_alerts.attributes.Description }} for your area, 
        it expires at {{ states.sensor.pws_alerts.attributes.Expires }}."
